version: "3.7"

services:
    revproxy:
        container_name: revproxy
        hostname: revproxy
        image: nginx:stable-alpine-slim
        restart: always
        volumes:
            - ./revproxy:/etc/nginx/conf.d
        ports:
            - 80:80
            - 443:443
        networks:
            - wschat-network

    backend:
        container_name: backend
        hostname: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        environment:
            BACKEND_PORT: "${BACKEND_PORT}"
        env_file:
            - ./.env
        expose:
            - ${BACKEND_PORT}
        networks:
            - wschat-network

    frontend:
        container_name: frontend
        hostname: frontend
        image: httpd:2.4.57-alpine3.18
        restart: always
        depends_on:
            - backend
        volumes:
            - ./frontend:/usr/local/apache2/htdocs
        env_file:
            - ./.env
        expose:
            - ${FRONTEND_PORT}
        networks:
            - wschat-network

networks:
    wschat-network:
        name: wschat-network
        driver: bridge
